[google_service_account]
type = "service_account"
project_id = "kpi-dashboard-new"
private_key_id = "55c1a73c7e2b88429359105abec637466119a941"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDilPLmCA1hZRHR
...
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@kpi-dashboard-new.iam.gserviceaccount.com"
client_id = "100528806182596802169"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40kpi-dashboard-new.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
