[google_service_account]
type = "service_account"
project_id = "kpi-dashboard-465407"
private_key_id = "a38ab89fe9598cedb871ff0a7b58137b1c89adcc"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9...  (your full private key contents)
-----END PRIVATE KEY-----\n"""
client_email = "your-service-account@kpi-dashboard-465407.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account@kpi-dashboard-465407.iam.gserviceaccount.com"
