[google_service_account]
type = "service_account"
project_id = "kpi-dashboard-new"
private_key_id = "55c1a73c7e2b88429359105abec637466119a941"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDilPLmCA1hZRHR
aiJbesGwvohd8iroIAJ+nV60W/JOOj18DSLuK6LGDozA3kIj9poapI6aXo6TOzTZ
PtRGW21Zs4Bkk7wCoQZvuynA03Ne5cfruxWypqJFsd4gruCEXfica2X2f3QpvWxw
Q1EcPuNd04ecxMfceYEA0CsL1zsqBSFTm+LMAcKGxZ0sma8A7sOPrbII6lWIxJid
6WhbUzZKaq6viYgwl1kluJjqJXOHJqcmE/t4af6r+Q+zE91FU5jC2Lt1tPWM0PRh
1QPpHIwe+Y8XbQzdBgxWOupoYcHeIK6ilRiMpXSpuBxQRpXcs2FbJ15wLWeUB+cb
VVSwQmHVAgMBAAECggEACBW9hxTBeXi0Ro8tc6sxLx/VWNjTzB2cSS1PXEstnbn5
SKxlUy9OaxfI0Pb9UDAz9oBpsDtwhfNmYtwZkfsgL0O28J/O5R8ezizVBBLnenrj
g9dUol/MyYTbwrnKvB5oSRiR9lY87GJcdLMKOWJLFaV/IMpqwUS6pC9JYe5Hp6uf
APzPMB1hfon79bApsdBEuWuoJq9M1sz9AV3q9WB2BYZNi2rTn/5ImrLXnHWuVJv6
yBJ6NSafP9/og5nCl4HSAxuzC2KcgNqD2pVNFAcKHtIy9i4ArU7Gx8NPDqBU3CIU
QJZ/nIc2DTN1hZkt3Tp59b+TR0NMM1Ay+5jBB2g18QKBgQDzamfBbir06LZ5+DlI
uPXvkSrs+o5aPTSQPPUunqorj0BJDhlTMEyci5qEbfVu3rbmmhQAfGiiIy7qptXu
LdJuZE5RdAV2wQ5ILVIXASbxwGrGpCCvpuczf6owTes5qpr7Tea7EIrSD9ZH8RWV
bF+VhSCQU8ySqOqi5aDL8f8VyQKBgQDuS7+wEkvDD+mIuIzppmVBgAdxG8ZivCxh
OyPPaFIv5f0DaQUHiQhGz+3E3bHt9yroAX1Zjdcrw9UapaMCmnFKO8Kcdr+nk/uF
RvDDRVN1fhr8THCPbM6KLaP1f7yYdjKDsTZOtAJE2Rna0wufBNfofjns8eUT6Edv
eTkzSGPhrQKBgQDnWh3NUflQFxLAcHV5shpGHVKQNEAycnPQF6/tJG6WwiuWg+j8
ES7vpxwwfBZGzzVFjfIu2A/W8tu3uOQh4blcpMdvUXeT/D+nyDN6m+S452pU7FAI
wviCEPffu18zyvxMmCkRaNKYfubqL7CU+ZELmqFtq8gHKLcCJoAi9xm8SQKBgQC0
mGvaAMOyPWj72QHSQe0TSvhY3HfpdDseJTfqhGFlM6Qg5YKOR2giYosMXAfxFRVL
Z3WcXUbpQC1NWKLF4k5huBCxi72MPzartyvYkb3CmaPR+gyEZi3Rwu0zrW89DLcT
30YNN5dQnkhd8vwns//9j0xPKrQ19h/Nd83F8+LesQKBgQDddhRFm/KVr0oHg+J7
LIFeU5k7wKckzQZCjoEnM3xDnyIN7paV0rvK8TVE29AoM2XK0sgKB58pGiYS3xr1
7nLQ8OstV80noRjPMm7hJ20AS9oMH8mA6IRa/spQaAy7FXZjiJZTX3Bve3kbSQKp
JROLhrxoBa0ImITBQw8eVepYrA==
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@kpi-dashboard-new.iam.gserviceaccount.com"
client_id = "100528806182596802169"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40kpi-dashboard-new.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
